/*
* Generated file
*
* Generated from: yang module name: protocol-framework yang module local name: reconnect-immediately-strategy-factory
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Jun 24 13:55:02 CEST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.bgp.protocol.framework;
public class ReconnectImmediatelyStrategyFactoryModuleFactory extends org.opendaylight.controller.config.yang.bgp.protocol.framework.AbstractReconnectImmediatelyStrategyFactoryModuleFactory {

}
