/**
* Generated file

* Generated from: yang module name: config-programming-impl  yang module local name: instruction-scheduler-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Nov 18 16:50:17 CET 2013
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.programming.impl;

/**
*
*/
public class InstructionSchedulerImplModuleFactory extends org.opendaylight.controller.config.yang.programming.impl.AbstractInstructionSchedulerImplModuleFactory
{


}
