/**
* Generated file

* Generated from: yang module name: config-pcep-spi  yang module local name: pcep-extensions-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Nov 18 14:32:53 CET 2013
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.pcep.spi;

/**
*
*/
public class SimplePCEPExtensionProviderContextModuleFactory extends org.opendaylight.controller.config.yang.pcep.spi.AbstractSimplePCEPExtensionProviderContextModuleFactory
{


}
