---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        exclude: '^.*/.*.bin'

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
      - id: remove-tabs
        stages: [commit]
        exclude: '^(.git/|docs/make.bat|docs/Makefile|.*/.*.bin)'

