/*
 * Copyright (c) 2016 Cisco Systems, Inc. and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

package org.opendaylight.protocol.bgp.evpn.impl.esi.types;

import com.google.common.base.Preconditions;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.Unpooled;
import org.opendaylight.protocol.util.ByteArray;
import org.opendaylight.protocol.util.ByteBufWriteUtil;
import org.opendaylight.yang.gen.v1.urn.ietf.params.xml.ns.yang.ietf.yang.types.rev100924.IetfYangUtil;
import org.opendaylight.yang.gen.v1.urn.ietf.params.xml.ns.yang.ietf.yang.types.rev100924.MacAddress;
import org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.bgp.evpn.rev160321.EsiType;
import org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.bgp.evpn.rev160321.esi.Esi;
import org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.bgp.evpn.rev160321.esi.esi.LacpAutoGeneratedCase;
import org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.bgp.evpn.rev160321.esi.esi.LacpAutoGeneratedCaseBuilder;
import org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.bgp.evpn.rev160321.esi.esi.lacp.auto.generated._case.LacpAutoGenerated;
import org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.bgp.evpn.rev160321.esi.esi.lacp.auto.generated._case.LacpAutoGeneratedBuilder;
import org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.bgp.evpn.rev160321.evpn.Evpn;
import org.opendaylight.yangtools.yang.common.QName;
import org.opendaylight.yangtools.yang.data.api.YangInstanceIdentifier.NodeIdentifier;
import org.opendaylight.yangtools.yang.data.api.schema.ContainerNode;

final class LacpParser extends AbstractEsiType {
    public static final NodeIdentifier LACP_NID_CASE = new NodeIdentifier(LacpAutoGeneratedCase.QNAME);
    static final NodeIdentifier LACP_NID = new NodeIdentifier(LacpAutoGenerated.QNAME);
    static final NodeIdentifier MAC_NID = NodeIdentifier.create(QName.create(Evpn.QNAME, "ce-lacp-mac-address").intern());
    static final NodeIdentifier PK_NID = NodeIdentifier.create(QName.create(Evpn.QNAME, "ce-lacp-port-key").intern());

    @Override
    public void serializeEsi(final Esi esi, final ByteBuf buffer) {
        Preconditions.checkArgument(esi instanceof LacpAutoGeneratedCase, "Unknown esi instance. Passed %s. Needed LacpAutoGeneratedCase.", esi
            .getClass());
        final ByteBuf body = Unpooled.buffer(ESI_TYPE_LENGTH);
        final LacpAutoGenerated lacp = ((LacpAutoGeneratedCase) esi).getLacpAutoGenerated();
        body.writeByte(EsiType.LacpAutoGenerated.getIntValue());
        body.writeBytes(IetfYangUtil.INSTANCE.bytesFor(lacp.getCeLacpMacAddress()));
        ByteBufWriteUtil.writeUnsignedShort(lacp.getCeLacpPortKey(), body);
        body.writeZero(ZERO_BYTE);
        buffer.writeBytes(body);
    }

    @Override
    public Esi serializeEsi(final ContainerNode esi) {
        final LacpAutoGeneratedBuilder builder = new LacpAutoGeneratedBuilder();
        builder.setCeLacpMacAddress(extractMac(esi));
        builder.setCeLacpPortKey(extractPK(esi));
        return new LacpAutoGeneratedCaseBuilder().setLacpAutoGenerated(builder.build()).build();

    }

    private Integer extractPK(final ContainerNode t1) {
        if (t1.getChild(PK_NID).isPresent()) {
            return (Integer) t1.getChild(PK_NID).get().getValue();
        }
        return null;
    }

    private MacAddress extractMac(final ContainerNode t1) {
        if (t1.getChild(MAC_NID).isPresent()) {
            return (MacAddress) t1.getChild(MAC_NID).get().getValue();
        }
        return null;
    }

    @Override
    public Esi parseEsi(final ByteBuf buffer) {
        final LacpAutoGenerated t1 = new LacpAutoGeneratedBuilder()
            .setCeLacpMacAddress(IetfYangUtil.INSTANCE.macAddressFor(ByteArray.readBytes(buffer, MAC_ADDRESS_LENGTH)))
            .setCeLacpPortKey(buffer.readUnsignedShort())
            .build();
        return new LacpAutoGeneratedCaseBuilder().setLacpAutoGenerated(t1).build();
    }
}
