/**
* Generated file

* Generated from: yang module name: config-bgp-topology-provider  yang module local name: bgp-reachability-ipv4
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Nov 19 15:13:57 CET 2013
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.bgp.rib.spi;

/**
*
*/
public class Ipv4ReachabilityTopologyBuilderModuleFactory extends org.opendaylight.controller.config.yang.bgp.rib.spi.AbstractIpv4ReachabilityTopologyBuilderModuleFactory
{


}
