/**
 * Generated file

 * Generated from: yang module name: reconnect-strategy  yang module local name: never-reconnect-strategy
 * Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
 * Generated at: Sat Nov 09 21:10:44 CET 2013
 *
 * Do not modify this file unless it is present under src/main directory
 */
package org.opendaylight.controller.config.yang.reconnectstrategy;

/**
*
*/
public class NeverReconnectStrategyModuleFactory
		extends
		org.opendaylight.controller.config.yang.reconnectstrategy.AbstractNeverReconnectStrategyModuleFactory {

}
