/**
 * Generated file

 * Generated from: yang module name: reconnect-strategy  yang module local name: reconnect-immediately-strategy
 * Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
 * Generated at: Sat Nov 09 21:48:04 CET 2013
 *
 * Do not modify this file unless it is present under src/main directory
 */
package org.opendaylight.controller.config.yang.reconnectstrategy;

/**
*
*/
public class ReconnectImmediatelyStrategyModuleFactory
		extends
		org.opendaylight.controller.config.yang.reconnectstrategy.AbstractReconnectImmediatelyStrategyModuleFactory {

}
