/*
 * Copyright (c) 2013 Cisco Systems, Inc. and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */
/**
* Generated file

* Generated from: yang module name: reconnect-strategy  yang module local name: timed-reconnect-strategy
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Nov 12 13:27:18 CET 2013
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.reconnectstrategy;

import org.opendaylight.controller.config.api.JmxAttributeValidationException;
import org.opendaylight.controller.config.reconnectstrategy.util.ReconnectStrategyCloseable;
import org.opendaylight.protocol.framework.ReconnectStrategy;
import org.opendaylight.protocol.framework.TimedReconnectStrategy;

/**
*
*/
public final class TimedReconnectStrategyModule extends org.opendaylight.controller.config.yang.reconnectstrategy.AbstractTimedReconnectStrategyModule
{

    public TimedReconnectStrategyModule(org.opendaylight.controller.config.api.ModuleIdentifier identifier, org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
        super(identifier, dependencyResolver);
    }

    public TimedReconnectStrategyModule(org.opendaylight.controller.config.api.ModuleIdentifier identifier, org.opendaylight.controller.config.api.DependencyResolver dependencyResolver, TimedReconnectStrategyModule oldModule, java.lang.AutoCloseable oldInstance) {
        super(identifier, dependencyResolver, oldModule, oldInstance);
    }

    @Override
    public void validate(){
		super.validate();
		JmxAttributeValidationException.checkNotNull(getSleepFactor(),
		"value is not set.", sleepFactorJmxAttribute);
		JmxAttributeValidationException.checkCondition(getSleepFactor()
				.doubleValue() >= 1,
				"value " + getSleepFactor() + " is less than 1",
				sleepFactorJmxAttribute);

		JmxAttributeValidationException.checkNotNull(getConnectTime(),
		"value is not set.", connectTimeJmxAttribute);
		JmxAttributeValidationException.checkCondition(getConnectTime() >= 0,
				"value " + getConnectTime() + " is less than 0",
				connectTimeJmxAttribute);

		JmxAttributeValidationException.checkNotNull(getMinSleep(),
		"value is not set.", minSleepJmxAttribute);
		JmxAttributeValidationException.checkCondition(
				getMaxSleep() == null || getMinSleep() <= getMaxSleep(),
				"value " + getMinSleep() + " is greter than MaxSleep " + getMaxSleep(),
				minSleepJmxAttribute);
    }

    @Override
    public java.lang.AutoCloseable createInstance() {
		ReconnectStrategy reconnectStrategy = new TimedReconnectStrategy(
				getExecutorDependency(), getConnectTime(), getMinSleep(),
				getSleepFactor().doubleValue(), getMaxSleep(),
				getMaxAttempts(), getDeadline());
		return new ReconnectStrategyCloseable(reconnectStrategy);
	}
}
