/**
* Generated file

* Generated from: yang module name: config-pcep-topology-provider  yang module local name: pcep-topology-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Nov 18 21:08:29 CET 2013
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.pcep.topology.provider;

/**
*
*/
public class PCEPTopologyProviderModuleFactory extends org.opendaylight.controller.config.yang.pcep.topology.provider.AbstractPCEPTopologyProviderModuleFactory
{


}
