/**
* Generated file

* Generated from: yang module name: config-pcep-topology-provider  yang module local name: pcep-topology-stateful02
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Jan 27 11:08:05 CET 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.pcep.topology.provider;

/**
*
*/
public class Stateful02TopologySessionListenerModuleFactory extends org.opendaylight.controller.config.yang.pcep.topology.provider.AbstractStateful02TopologySessionListenerModuleFactory
{


}
