/*
 * Copyright (c) 2014 Cisco Systems, Inc. and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */
/**
 * Generated file
 * <p>
 * Generated from: yang module name: config-pcep-topology-provider  yang module local name: pcep-topology-stateful07
 * Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
 * Generated at: Mon Jan 27 11:08:05 CET 2014
 * <p>
 * Do not modify this file unless it is present under src/main directory
 */
package org.opendaylight.controller.config.yang.pcep.topology.provider;

/**
 * @deprecated Replaced by blueprint wiring
 */
public class Stateful07TopologySessionListenerModuleFactory extends
        AbstractStateful07TopologySessionListenerModuleFactory {
}
