#
# Copyright (c) 2025 PANTHEON.tech, s.r.o. and others.  All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this distribution,
# and is available at http://www.eclipse.org/legal/epl-v10.html
#

from enum import IntEnum, auto


class SuiteOrder(IntEnum):
    """Defines the execution order of all test suites."""

    BGP_INGEST_PC_SHM_300K = auto()
    BGP_INGEST_SINGLEPEER_PREFIX_COUNT = auto()
    BGP_INGEST_SINGLEPEER_CHANGE_COUNT = auto()
    BGP_INGEST_APP_SINGLEPEER_PREFIX_COUNT = auto()
    BGP_INGEST_MANYPEERS_CHANGE_COUNT = auto()
    BGP_INGEST_APP_MANYPEERS_PREFIX_COUNT = auto()
    BGP_INGEST_MANYPEERS_PREFIX_COUNT = auto()
    BGP_INGEST_MIXED_SINGLEPEER_PREFIX_COUNT = auto()
    BGP_INGEST_MIXED_SINGLEPEER_CHANGE_COUNT = auto()
    BGP_INGEST_MIXED_MANYPEERS_PREFIX_COUNT = auto()
    BGP_INGEST_MIXED_MANYPEERS_CHANGE_COUNT = auto()
    BGP_THROUGHPCEP_SINGLE_PCC = auto()
    BGP_THROUGHPCEP_MANY_PCCS = auto()
    BGP_USER_FLOWSPEC = auto()
    BGP_USER_L3VPN = auto()
    BGP_USER_EVPN = auto()
    BGP_USER_BMP = auto()
    BGP_USER_MVPN = auto()
    BGP_USER_L3VPN_MCAST = auto()
    BGP_USER_RT_CONSTRAIN = auto()
    BGP_USER_BASIC = auto()
    BGP_USER_APP_PEER = auto()
    BGP_USER_MD5 = auto()
    BGP_USER_IPV6 = auto()
    BGP_USER_LLGR = auto()
    BGP_USER_IBGP_PEERS = auto()
    BGP_USER_PCEP = auto()
    BGP_USER_EBGP_PEERS = auto()
    BGP_USER_IBGP_LSP = auto()
    BGP_USER_ROUTE_REF = auto()
    BGP_USER_MULTIPATH = auto()
    BGP_USER_RT_CONSTRAIN_VALIDATION = auto()
    BGP_USER_POLICIES = auto()
    BGP_USER_TCP_MD5 = auto()
    BGP_USER_MANY_FLOWSPEC = auto()
    BGP_USER_MANY_L3VPN = auto()
    BGP_USER_MANY_EVPN = auto()
    BGP_USER_MANY_BMP = auto()
    BGP_USER_MANY_MVPN = auto()
    BGP_USER_MANY_L3VPN_MCAST = auto()
    BGP_USER_MANY_RT_CONSTRAIN = auto()
    BGP_USER_MANY_BASIC = auto()
    BGP_USER_MANY_APP_PEER = auto()
    BGP_USER_MANY_MD5 = auto()
    BGP_USER_MANY_IPV6 = auto()
    BGP_USER_MANY_LLGR = auto()
    BGP_USER_MANY_IBGP_PEERS = auto()
    BGP_USER_MANY_PCEP = auto()
    BGP_USER_MANY_EBGP_PEERS = auto()
    BGP_USER_MANY_IBGP_LSP = auto()
    BGP_USER_MANY_ROUTE_REF = auto()
    BGP_USER_MANY_MULTIPATH = auto()
    BGP_USER_MANY_RT_CONSTRAIN_VALIDATION = auto()
    BGP_USER_MANY_POLICIES = auto()
    BGP_USER_MANY_TCP_MD5 = auto()
    PCEP_STAT_TC1 = auto()
    PCEP_STAT_TC2 = auto()
    PCEP_STAT_TC3 = auto()
    PCEP_STAT_TC4 = auto()
    PCEP_STAT_TC5 = auto()
    PCEP_STAT_TC6 = auto()
    PCEP_STAT_TC7 = auto()
    PCEP_STAT_TC8 = auto()
    PCEP_STAT_TC9 = auto()
    PCEP_STAT_TC10 = auto()
    PCEP_STAT_TC11 = auto()
    PCEP_STAT_TC12 = auto()
