/*
* Generated file
*
* Generated from: yang module name: odl-bmp-impl-cfg yang module local name: bmp-monitor-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon May 18 15:47:07 CEST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.bmp.impl;
public class BmpMonitorImplModuleFactory extends org.opendaylight.controller.config.yang.bmp.impl.AbstractBmpMonitorImplModuleFactory {

}
