/*
* Generated file
*
* Generated from: yang module name: odl-bgp-labeled-unicast-cfg yang module local name: bgp-labeled-unicast
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sun Jun 07 18:36:59 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.bgp.labeled_unicast;
public class LabeledUnicastModuleFactory extends org.opendaylight.controller.config.yang.bgp.labeled_unicast.AbstractLabeledUnicastModuleFactory {

}
