/*
* Generated file
*
* Generated from: yang module name: odl-rsvp-parser-impl-cfg yang module local name: rsvp-parser
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Aug 27 13:07:00 CEST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.rsvp.parser.impl;
public class RSVPParserModuleFactory extends org.opendaylight.controller.config.yang.rsvp.parser.impl.AbstractRSVPParserModuleFactory {

}
