/**
* Generated file

* Generated from: yang module name: config-bgp-linkstate  yang module local name: bgp-linkstate
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Nov 16 08:52:43 CET 2013
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.bgp.linkstate;

/**
*
*/
public class LinkstateModuleFactory extends org.opendaylight.controller.config.yang.bgp.linkstate.AbstractLinkstateModuleFactory
{


}
