/*
* Generated file
*
* Generated from: yang module name: odl-bgp-flowspec-cfg yang module local name: bgp-flowspec
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Apr 23 09:35:52 CEST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.bgp.flowspec;
public class FlowspecModuleFactory extends org.opendaylight.controller.config.yang.bgp.flowspec.AbstractFlowspecModuleFactory {

}
