/**
* Generated file

* Generated from: yang module name: bgp-rib-impl  yang module local name: base-bgp-rib
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Dec 03 09:13:09 CET 2013
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.bgp.rib.impl;

/**
*
*/
public class BaseBGPRIBModuleFactory extends org.opendaylight.controller.config.yang.bgp.rib.impl.AbstractBaseBGPRIBModuleFactory
{


}
