/**
 * Generated file

 * Generated from: yang module name: bgp-rib-impl  yang module local name: bgp-impl
 * Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
 * Generated at: Wed Nov 06 13:02:31 CET 2013
 *
 * Do not modify this file unless it is present under src/main directory
 */
package org.opendaylight.controller.config.yang.bgp.rib.impl;

/**
*
*/
public class BGPImplModuleFactory
		extends
		org.opendaylight.controller.config.yang.bgp.rib.impl.AbstractBGPImplModuleFactory {

}
