/**
* Generated file

* Generated from: yang module name: bgp-rib-impl  yang module local name: bgp-rib-extensions-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Nov 15 17:49:05 CET 2013
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.bgp.rib.impl;

/**
*
*/
public class RIBExtensionsImplModuleFactory extends org.opendaylight.controller.config.yang.bgp.rib.impl.AbstractRIBExtensionsImplModuleFactory
{


}
