/**
 * Generated file

 * Generated from: yang module name: bgp-rib-impl  yang module local name: bgp-rib-extensions-impl
 * Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
 * Generated at: Fri Nov 15 17:49:05 CET 2013
 *
 * Do not modify this file unless it is present under src/main directory
 */
package org.opendaylight.controller.config.yang.bgp.rib.impl;

import org.opendaylight.protocol.bgp.rib.impl.RIBExtensionProviderContextImpl;

/**
 *
 */
public final class RIBExtensionsImplModule extends org.opendaylight.controller.config.yang.bgp.rib.impl.AbstractRIBExtensionsImplModule
{

	public RIBExtensionsImplModule(final org.opendaylight.controller.config.api.ModuleIdentifier identifier, final org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
		super(identifier, dependencyResolver);
	}

	public RIBExtensionsImplModule(final org.opendaylight.controller.config.api.ModuleIdentifier identifier, final org.opendaylight.controller.config.api.DependencyResolver dependencyResolver, final RIBExtensionsImplModule oldModule, final java.lang.AutoCloseable oldInstance) {
		super(identifier, dependencyResolver, oldModule, oldInstance);
	}

	@Override
	public void validate(){
		super.validate();
		// Add custom validation for module attributes here.
	}

	@Override
	public java.lang.AutoCloseable createInstance() {
		final class RIBExtensionProviderContextImplCloseable extends RIBExtensionProviderContextImpl implements AutoCloseable {
			@Override
			public void close() {

			}
		}

		return new RIBExtensionProviderContextImplCloseable();
	}
}
