/**
 * Generated file

 * Generated from: yang module name: bgp-rib-impl  yang module local name: rib-impl
 * Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
 * Generated at: Wed Nov 06 13:02:32 CET 2013
 *
 * Do not modify this file unless it is present under src/main directory
 */
package org.opendaylight.controller.config.yang.bgp.rib.impl;

/**
*
*/
public class RIBImplModuleFactory
		extends
		org.opendaylight.controller.config.yang.bgp.rib.impl.AbstractRIBImplModuleFactory {

}
