/*
* Generated file
*
* Generated from: yang module name: bgp-rib-impl yang module local name: strict-bgp-peer-acceptor
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Jul 02 13:11:48 CEST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.bgp.rib.impl;
public class StrictBGPPeerAcceptorModuleFactory extends org.opendaylight.controller.config.yang.bgp.rib.impl.AbstractStrictBGPPeerAcceptorModuleFactory {

}
