/*
* Generated file
*
* Generated from: yang module name: odl-bgp-parser-spi-cfg yang module local name: rsvp-extensions-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Aug 26 11:44:42 CEST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.rsvp.parser.spi;
public class SimpleRSVPExtensionProviderContextModuleFactory extends org.opendaylight.controller.config.yang.rsvp.parser.spi.AbstractSimpleRSVPExtensionProviderContextModuleFactory {

}
