/*
 * Copyright (c) 2016 Cisco Systems, Inc. and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/* Generated file
*
* Generated from: yang module name: odl-bgp-rib-impl-cfg yang module local name: add-path-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Feb 04 12:29:55 CET 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.bgp.rib.impl;
public class AddPathImplModuleFactory extends org.opendaylight.controller.config.yang.bgp.rib.impl.AbstractAddPathImplModuleFactory {

}
