/**
* Generated file

* Generated from: yang module name: odl-pcep-impl-cfg  yang module local name: pcep-parser-base
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Dec 03 09:34:06 CET 2013
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.pcep.impl;

/**
*
*/
public class BasePCEPParserModuleFactory extends org.opendaylight.controller.config.yang.pcep.impl.AbstractBasePCEPParserModuleFactory
{


}
