/**
 * Generated file

 * Generated from: yang module name: odl-pcep-impl-cfg  yang module local name: pcep-parser-crabbe-initiated00
 * Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
 * Generated at: Wed Jan 22 15:11:39 CET 2014
 *
 * Do not modify this file unless it is present under src/main directory
 */
package org.opendaylight.controller.config.yang.pcep.impl;

import org.opendaylight.protocol.pcep.crabbe.initiated00.InitiatedActivator;

/**
*
*/
public final class CrabbeInitiated00PCEPParserModule extends
		org.opendaylight.controller.config.yang.pcep.impl.AbstractCrabbeInitiated00PCEPParserModule {

	public CrabbeInitiated00PCEPParserModule(final org.opendaylight.controller.config.api.ModuleIdentifier identifier,
			final org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
		super(identifier, dependencyResolver);
	}

	public CrabbeInitiated00PCEPParserModule(final org.opendaylight.controller.config.api.ModuleIdentifier identifier,
			final org.opendaylight.controller.config.api.DependencyResolver dependencyResolver,
			final CrabbeInitiated00PCEPParserModule oldModule, final java.lang.AutoCloseable oldInstance) {

		super(identifier, dependencyResolver, oldModule, oldInstance);
	}

	@Override
	public java.lang.AutoCloseable createInstance() {
		return new InitiatedActivator();
	}
}
