/**
* Generated file

* Generated from: yang module name: odl-pcep-impl-cfg  yang module local name: pcep-parser-ietf-stateful02
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Jan 22 15:11:39 CET 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.pcep.impl;

/**
*
*/
public class IetfStateful02PCEPParserModuleFactory extends org.opendaylight.controller.config.yang.pcep.impl.AbstractIetfStateful02PCEPParserModuleFactory
{


}
