/**
 * Generated file

 * Generated from: yang module name: pcep-impl  yang module local name: pcep-session-proposal-factory-impl
 * Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
 * Generated at: Wed Nov 06 13:16:39 CET 2013
 *
 * Do not modify this file unless it is present under src/main directory
 */
package org.opendaylight.controller.config.yang.pcep.impl;

import java.net.InetSocketAddress;

import org.opendaylight.controller.config.api.JmxAttributeValidationException;
import org.opendaylight.protocol.pcep.PCEPSessionProposalFactory;
import org.opendaylight.protocol.pcep.impl.PCEPSessionProposalFactoryImpl;
import org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.pcep.types.rev131005.open.object.Open;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
*
*/
public final class PCEPSessionProposalFactoryImplModule
		extends
		org.opendaylight.controller.config.yang.pcep.impl.AbstractPCEPSessionProposalFactoryImplModule {
	
	private static final Logger logger = LoggerFactory.getLogger(PCEPSessionProposalFactoryImplModule.class);

	public PCEPSessionProposalFactoryImplModule(
			org.opendaylight.controller.config.api.ModuleIdentifier name,
			org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
		super(name, dependencyResolver);
	}

	public PCEPSessionProposalFactoryImplModule(
			org.opendaylight.controller.config.api.ModuleIdentifier name,
			org.opendaylight.controller.config.api.DependencyResolver dependencyResolver,
			PCEPSessionProposalFactoryImplModule oldModule,
			java.lang.AutoCloseable oldInstance) {
		super(name, dependencyResolver, oldModule, oldInstance);
	}

	@Override
	public void validate() {
		super.validate();
		JmxAttributeValidationException.checkNotNull(getActive(),
				"value is not set.", activeJmxAttribute);
		JmxAttributeValidationException.checkNotNull(getVersioned(),
				"value is not set.", versionedJmxAttribute);
		JmxAttributeValidationException.checkNotNull(getTimeout(),
				"value is not set.", timeoutJmxAttribute);
		JmxAttributeValidationException.checkNotNull(getInstantiated(),
				"value is not set.", instantiatedJmxAttribute);
		JmxAttributeValidationException.checkNotNull(getDeadTimerValue(),
				"value is not set.", deadTimerValueJmxAttribute);
		JmxAttributeValidationException.checkNotNull(getKeepAliveTimerValue(),
				"value is not set.", keepAliveTimerValueJmxAttribute);
		if (getKeepAliveTimerValue() != 0) {
			JmxAttributeValidationException.checkCondition(
					getKeepAliveTimerValue() >= 1, "minimum value is 1.",
					keepAliveTimerValueJmxAttribute);
			if (getDeadTimerValue() != 0 && (getDeadTimerValue() / getKeepAliveTimerValue() == 4)) {
				logger.warn("DeadTimerValue should be 4 times greater than KeepAliveTimerValue");
			}
		}
		if ((getActive() || getVersioned() || getTimeout() > 0)
				&& !getStateful())
			setStateful(true);
		JmxAttributeValidationException.checkNotNull(getStateful(),
				"value is not set.", statefulJmxAttribute);
	}

	@Override
	public java.lang.AutoCloseable createInstance() {
		PCEPSessionProposalFactoryImpl inner = new PCEPSessionProposalFactoryImpl(
				getDeadTimerValue(), getKeepAliveTimerValue(), getStateful(),
				getActive(), getVersioned(), getInstantiated(), getTimeout());
		return new PCEPSessionProposalFactoryCloseable(inner);
	}

	private static final class PCEPSessionProposalFactoryCloseable implements
			PCEPSessionProposalFactory, AutoCloseable {

		private PCEPSessionProposalFactoryImpl inner;

		public PCEPSessionProposalFactoryCloseable(
				PCEPSessionProposalFactoryImpl inner) {
			this.inner = inner;
		}

		@Override
		public void close() throws Exception {
		}

		@Override
		public Open getSessionProposal(InetSocketAddress inetSocketAddress,
				int i) {
			return inner.getSessionProposal(inetSocketAddress, i);
		}
	}
}
