/**
* Generated file

* Generated from: yang module name: odl-pcep-impl-cfg  yang module local name: pcep-parser-stateful
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Jan 14 11:25:06 CET 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.pcep.impl;

/**
*
*/
public class StatefulPCEPParserModuleFactory extends org.opendaylight.controller.config.yang.pcep.impl.AbstractStatefulPCEPParserModuleFactory
{


}
