/*
* Generated file
*
* Generated from: yang module name: odl-bgp-rib-spi-cfg yang module local name: timed-reconnect-strategy-factory
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Jun 23 11:37:10 CEST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.bgp.rib.spi;
public class TimedReconnectStrategyFactoryModuleFactory extends org.opendaylight.controller.config.yang.bgp.rib.spi.AbstractTimedReconnectStrategyFactoryModuleFactory {

}
