/**
* Generated file

* Generated from: yang module name: config-bgp-parser-spi  yang module local name: bgp-extensions-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Nov 18 10:44:24 CET 2013
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.bgp.parser.spi;

/**
*
*/
public class SimpleBGPExtensionProviderContextModuleFactory extends org.opendaylight.controller.config.yang.bgp.parser.spi.AbstractSimpleBGPExtensionProviderContextModuleFactory
{


}
