filter:
    excluded_paths:
        - 'lib/exabgp/dep/*'
        - 'bin/*'
        - 'sbin/*'
        - 'etc/*'
        - 'dev/*'
        - 'qa/*'
        - 'debian/*'
        - 'service/*'
        - 'build/*'
        - 'dist/*'
    paths: {  }
tools:
    python_analyzer:
        enabled: true
        config:
            metrics: true
            duplication_detector:
                enabled: true
                min_mass: 25
        file_extensions:
            - .py
        filter:
            excluded_paths:
                - 'lib/exabgp/dep/*'
                - 'bin/*'
                - 'sbin/*'
                - 'etc/*'
                - 'dev/*'
                - 'qa/*'
                - 'debian/*'
                - 'service/*'
                - 'build/*'
                - 'dist/*'
            paths: {  }
    pylint:
        enabled: true
        python_version: '2'
        plugins: {  }
        config_file: '.pylintrc'
        filter:
            excluded_paths:
                - 'lib/exabgp/dep/*'
                - 'bin/*'
                - 'sbin/*'
                - 'etc/*'
                - 'dev/*'
                - 'qa/*'
                - 'debian/*'
                - 'service/*'
                - 'build/*'
                - 'dist/*'
            paths: {  }
    external_code_coverage:
        timeout: 600
