/*
* Generated file
*
* Generated from: yang module name: odl-openconfig-bgp-cfg yang module local name: openconfig-bgp
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Jul 18 18:32:31 CEST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.bgp.openconfig;
public class BgpOpenonfigImplModuleFactory extends org.opendaylight.controller.config.yang.bgp.openconfig.AbstractBgpOpenonfigImplModuleFactory {

}
